//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tao.LAS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tao.LAS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAS analysis complete.
        /// </summary>
        internal static string analysis_complete {
            get {
                return ResourceManager.GetString("analysis_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Username.
        /// </summary>
        internal static string Form1_cboUserName_Username {
            get {
                return ResourceManager.GetString("Form1_cboUserName_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Usernames.
        /// </summary>
        internal static string Form1_cboUserName_Usernames {
            get {
                return ResourceManager.GetString("Form1_cboUserName_Usernames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 Records Found..
        /// </summary>
        internal static string Form1_GetTab1Data__0_Records_Found_ {
            get {
                return ResourceManager.GetString("Form1_GetTab1Data__0_Records_Found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Records Found..
        /// </summary>
        internal static string Form1_GetTab1Data__Records_Found_ {
            get {
                return ResourceManager.GetString("Form1_GetTab1Data__Records_Found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string Form1_NewLineCharacters {
            get {
                return ResourceManager.GetString("Form1_NewLineCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string Form1_UpdateStatusStrip_Percent {
            get {
                return ResourceManager.GetString("Form1_UpdateStatusStrip_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has added blog.
        /// </summary>
        internal static string PageParser_Const_Blogged {
            get {
                return ResourceManager.GetString("PageParser_Const_Blogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has added a comment to .
        /// </summary>
        internal static string PageParser_Const_Comment {
            get {
                return ResourceManager.GetString("PageParser_Const_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voted.
        /// </summary>
        internal static string PageParser_Const_CommentVote {
            get {
                return ResourceManager.GetString("PageParser_Const_CommentVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to down!.
        /// </summary>
        internal static string PageParser_Const_Down {
            get {
                return ResourceManager.GetString("PageParser_Const_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites!.
        /// </summary>
        internal static string PageParser_Const_Favourited {
            get {
                return ResourceManager.GetString("PageParser_Const_Favourited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voted on item.
        /// </summary>
        internal static string PageParser_Const_ItemVote {
            get {
                return ResourceManager.GetString("PageParser_Const_ItemVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has registered!.
        /// </summary>
        internal static string PageParser_Const_Registered {
            get {
                return ResourceManager.GetString("PageParser_Const_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has subscribed to channel.
        /// </summary>
        internal static string PageParser_Const_Subscribed {
            get {
                return ResourceManager.GetString("PageParser_Const_Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  voted .
        /// </summary>
        internal static string PageParser_Const_Thumbed {
            get {
                return ResourceManager.GetString("PageParser_Const_Thumbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has unsubscribed from channel.
        /// </summary>
        internal static string PageParser_Const_Unsubscribed {
            get {
                return ResourceManager.GetString("PageParser_Const_Unsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up!.
        /// </summary>
        internal static string PageParser_Const_Up {
            get {
                return ResourceManager.GetString("PageParser_Const_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in channel .
        /// </summary>
        internal static string PageParser_Const_Uploaded {
            get {
                return ResourceManager.GetString("PageParser_Const_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time taken:.
        /// </summary>
        internal static string Total_time_taken {
            get {
                return ResourceManager.GetString("Total_time_taken", resourceCulture);
            }
        }
    }
}
